name: nestya
description: "Nestya application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_code_metrics: ^5.7.6
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true