name: Backend CI/CD
on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build-push-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ['self-hosted', 'Linux', 'X64']
    steps:
      - uses: actions/checkout@v4

      - name: Image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/nestya-backend:${{ steps.vars.outputs.TAG }} backend
          docker tag  ${{ secrets.REGISTRY_URL }}/nestya-backend:${{ steps.vars.outputs.TAG }} ${{ secrets.REGISTRY_URL }}/nestya-backend:latest

      - name: Push image
        run: |
          docker push ${{ secrets.REGISTRY_URL }}/nestya-backend:${{ steps.vars.outputs.TAG }}
          docker push ${{ secrets.REGISTRY_URL }}/nestya-backend:latest

      - name: Deploy (SSH to App VM)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.APP_SSH_HOST }}
          username: ${{ secrets.APP_SSH_USER }}
          key: ${{ secrets.APP_SSH_KEY }}
          script: |
            cd /srv/nestya
            sed -i "s/^BACKEND_TAG=.*/BACKEND_TAG=${{ steps.vars.outputs.TAG }}/" .env
            docker compose pull backend
            docker compose up -d backend
            docker compose ps
